### ISSUE TITLE
无法保存阅读进度

### ISSUE THREAD

**Issue by synhi** [jijinggang/sumatrapdf#1]
试用了一下，中文排版的确是比官网下载的好很多，但是因为是单文件版本，所以无法保存阅读进度（官网的单文件版本也无法保存进度），有些不方便，不知能否做出 32 位和 64 为的安装版

**Comment by jijinggang** [comment]
![image](https://user-images.githubusercontent.com/330505/34759339-11b50e9e-f616-11e7-897e-c5d839b4eeec.png)
参见这个配置项,能打开多文件,能保存文件进度

**Comment by llinfeng** [comment]
我这儿验证过了，配合“记住已打开的文件”，是能保存阅读进度的。

**Comment by jijinggang** [comment]
是的,这个跟原版是完全一样的
